
import gradio as gr
import numpy as np 
import config
from utils import *
import torch.optim as optim 
from model import generator, Discriminator
gen_A = generator(img_channels=3).to(config.DEVICE)
gen_B = generator(img_channels=3).to(config.DEVICE)
opt_gen = optim.Adam(
        list(gen_A.parameters()) + list(gen_B.parameters()),
        lr=config.LEARNING_RATE,
        betas=(0.5, 0.999)
    )
load_checkpoint(config.CHECKPOINT_GEN_B, gen_B, opt_gen, config.LEARNING_RATE),
load_checkpoint(config.CHECKPOINT_GEN_A, gen_A, opt_gen, config.LEARNING_RATE),
def winter2summer(image:np.ndarray):
    summer_image = gen_B(image)
    return summer_image
def summer2winter(image:np.ndarray):
    winter_image = gen_A(image)
    return winter_image
     

def main():
    with gr.Blocks(css="footer {visibility: hidden}",theme=gr.themes.Soft()) as demo:
        gr.Markdown("""<center><font size=10>Cycle GAN demo</center>""")
        with gr.Row(equal_height=False):
            file_output = gr.Files(height=200)
            df_process = gr.DataFrame(scale=1, height=350,interactive=False,wrap=True)
            sumbit = gr.Button("🚀 submit")
        with gr.Row(equal_height=False):
            
            df = gr.outputs.Dataframe(type='pandas')
            gallery = gr.Gallery(label="plots of the data",preview = False).style(height='auto',columns=2)
        with gr.Row(equal_height=False):
                chatbot = gr.Chatbot(label='final report',scale=1)
                with gr.Column():
                    textbox_out = gr.Textbox(lines=3, label='SQL statement generated by llms')
                    textbox = gr.Textbox(lines=3, label='send your question about the data')
                    with gr.Row():
                        clear_history = gr.Button("🧹 clear")
                        sumbit = gr.Button("🚀 submit")
        # file_output.upload(llm_instance.process_file, inputs= [file_output],outputs=[df_process])
        # sumbit.click(llm_instance.model_chat, [textbox, chatbot, df_process], [textbox_out, chatbot, gallery, df])
        # clear_history.click(fn=normal.clear_session,
        #                     inputs=[],
        #                     outputs=[textbox, textbox_out, chatbot, gallery, df, df_process])
    demo.queue(api_open=False).launch(max_threads=10, height=800, share=False)
if __name__ == "__main__":
    main()